### PR TITLE
feat(rust): fix output formatting of ockam node list

### LINKED ISSUE #5384: Improve spacing in output when calling `ockam node list`
### Observed behavior

Calling the below
```bash
ockam node create n1
ockam node create n2
```
and then calling `ockam node list` give inconsistent output
```
       ┌───────────────────┐
       │       Nodes       │
       └───────────────────┘
     │ Node n1 (default) UP
     │ Process id 57293

     │ Node n2  UP
     │ Process id 57405
```
`Node n2  UP` adds an extra unneeded space

### Expected behavior

On calling `ockam node list` we should not get irregular spacing in output

### Ockam Version

ockam v0.90.0

### PR DESCRIPTION
**Pull request by qxtaiba**
## Current behavior

In the original implementation of NodeListOutput, when the `self.is_default` field is `false`, an extra whitespace appears in the output when using `format!` macro to construct the final output string.

## Proposed changes

The issue that this PR fixes is described in #5384.

In this fix, the default variable is defined appropriately based on the value of `self.is_default`. In the case that `self.is_default` is `true`, the default variable holds the value " (default)", which includes a space before the "(default)" string. In the case that `self.is_default` is `false`, the default variable holds an empty string, which contains no visible characters.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

### CODE REVIEW

File: implementations/rust/ockam/ockam_command/src/node/list.rs [hunk 1]
```diff
@@ -141,18 +142,20 @@ impl Output for NodeListOutput {
...
-        let output = format!(
-            r#"Node {node_name} {default} {status}
-{pid}"#,
-            node_name = self
-                .node_name
-                .to_string()
-                .color(OckamColor::PrimaryResource.color()),
-        );
+        let mut output = String::new();
+        write!(
```
Comment (shanesveller) [inline implementations/rust/ockam/ockam_command/src/node/list.rs]: Was there some aspect that did not behave correctly when using `format`? If it works fine, I think we'd probably prefer to continue using that style and syntax here and only adjust the whitespace.

Comment (adrianbenavides) [reply implementations/rust/ockam/ockam_command/src/node/list.rs]: In case you did this to avoid the weird new line formatting that we had before, you can use `formatdoc`:

```rust
let output = formatdoc! {"
    Node {node_name}{default} {status}
    {pid}",
    node_name = self
        .node_name
        .to_string()
        .color(OckamColor::PrimaryResource.color()),
};
```

Comment (qxtaiba) [reply implementations/rust/ockam/ockam_command/src/node/list.rs]: Thanks. My latest commit uses `formatdoc` instead to get around new line formatting. 

@shanesveller If you prefer I leave this implemented with `format` then also happy to do that. Let me know!

Comment (shanesveller) [reply implementations/rust/ockam/ockam_command/src/node/list.rs]: No need if `formatdoc` also helped, but thanks for checking!

File: implementations/rust/ockam/ockam_command/src/node/list.rs [hunk 2]
```diff
@@ -141,18 +142,19 @@ impl Output for NodeListOutput {
...
 
-        let output = format!(
-            r#"Node {node_name} {default} {status}
-{pid}"#,
-            node_name = self
-                .node_name
-                .to_string()
-                .color(OckamColor::PrimaryResource.color()),
-        );
+        let output = formatdoc! {"
```
Comment (davide-baldo) [inline implementations/rust/ockam/ockam_command/src/node/list.rs:149]: nice!

**Review by davide-baldo — APPROVED** [review]
LGTM
