### PR TITLE
chore(rust): fix for `node create /node/n1` bug

### LINKED ISSUE #4137: Diagnose and fix `ockam node create /node/n1` error
## Currently

Fails when passing a `MultiAddr` as a node name.

## Desired

This command only needs to extract the node name from the `node_name` argument (i.e. it doesn't need to transform it in any way). Currently, the command will take the command argument value as is, whereas we also need to support valid MultiAddr strings with the format `/node/{name}`.

To support both inputs, the argument type must be `String` so it can be processed with the [`extract_address_value` function](https://github.com/build-trust/ockam/blob/f1b551e0e69cefeaa52133c4dd84546d38cab4cb/implementations/rust/ockam/ockam_command/src/util/mod.rs#L450) function. You can check how this function works in the [unit tests](https://github.com/build-trust/ockam/blob/f1b551e0e69cefeaa52133c4dd84546d38cab4cb/implementations/rust/ockam/ockam_command/src/util/mod.rs#L542).

A potential solution would be to create a wrapper function around `extract_address_value` with the following logic:
- If the input string is a multiaddr, then check that it's of type `Node`. If it's not, then return an error saying that the input MultiAddr must follow the format `/node/{name}`. If it is, call the `extract_address_value` function
- else, return the input unprocessed

## How to reproduce the error

```bash
» ockam node create /node/n2
Version 0.78.0, hash: 7b1d00e8b11881d6b7c422f9e7acc4c77bbc7ba5
IO error

Caused by:
Read-only file system (os error 30)
```

### PR DESCRIPTION
**Pull request by nidnogg**
## Current Behavior

Whenever a node is created via `node create <node_name>` and `node_name` is a `MultiAddr` String, an IO error is produced. 

## Proposed Changes

This PR fixes #4137 by adding a `parse_node_name()` function before the node's creation that uses the `extract_address_value` util (when applicable) to circumvent this.

## Checks

- [X] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [X] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [X] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

### CODE REVIEW

File: implementations/rust/ockam/ockam_command/src/node/create.rs [hunk 1]
```diff
@@ -144,6 +144,23 @@ impl CreateCommand {
             ..cmd
         })
     }
+
+    fn parse_node_name(&self) -> crate::Result<Self> {
+        let cmd = self.clone();
+
+        if self.node_name.contains('/') {
+            if self.node_name.starts_with("/node/") {
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_command/src/node/create.rs]: This is a little hack we should avoid as it doesn't express what we are trying to parse here. You should parse the string into a MultiAddr instance and check the protocol like it's done inside `extract_address_value`. It's more verbose, but it doesn't depend on manual/hard-coded parsing rules.

File: implementations/rust/ockam/ockam_command/src/node/create.rs [hunk 2]
```diff
@@ -144,6 +144,23 @@ impl CreateCommand {
...
+                let node_name = extract_address_value(&self.node_name)?;
+                return Ok(Self { node_name, ..cmd });
+            } else {
+                return Err(crate::Error::new(
+                    exitcode::IOERR,
+                    anyhow!("Error: A MultiAddr node must follow the format /node/{{name}}"),
+                ));
+            }
+        }
+        Ok(Self { ..cmd })
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_command/src/node/create.rs]: This function should be static and should live in the utils.rs close to the `extract_address_value` and should return a `String` so we can reuse it elsewhere if needed. The input should be a `&str` too.

File: implementations/rust/ockam/ockam_command/src/node/create.rs (hunk 1 above)
Comment (nidnogg) [reply implementations/rust/ockam/ockam_command/src/node/create.rs]: Modified it in the latest commit to work similarly to `extract_address_value`

File: implementations/rust/ockam/ockam_command/src/node/create.rs (hunk 2 above)
Comment (nidnogg) [reply implementations/rust/ockam/ockam_command/src/node/create.rs]: Return types changed and function moved closer to `extract_address_value` for reusability in the latest commit

**Review by adrianbenavides — DISMISSED** [review]
Looks perfect, thank you so much @nidnogg for this great contribution!

**Review by adrianbenavides — APPROVED** [review]
