### PR TITLE
fix(rust): fix panic hang in task during ockam lease call

### LINKED ISSUE #5674: ockam_command hangs when calling `lease` on an uninitialized project
### Observed behavior

If you run `ockam lease --token_id 1234` before a project has been initialized, it will panic.  However since the panic happens within an async task, the program hangs rather than shutting down.

Specifically here:
https://github.com/build-trust/ockam/blob/3c06be25cd02794016562af33d2e55f765142539/implementations/rust/ockam/ockam_command/src/util/orchestrator_api.rs#L210

A crtl-C is required to return to the terminal prompt.

The printed message is
```
thread 'tokio-runtime-worker' panicked at 'A default project or project parameter is required: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

This is somewhat related to #5633 

### Steps to reproduce

1. remove `~/.ockam`
2. run `ockam lease --token_id 1234`

### Expected behavior

The application should return an Error to notify the user that a project must be initialized prior to calling `lease` and shutdown gracefully.

### Ockam Version

0.90.0

### PR DESCRIPTION
**Pull request by seve-martinez**
## Current behavior
Closes #5674.

If `ockam lease --token_id` is called prior to an initialized project, or without a project parameter, the application will hang due to a panic within an async task.

The panic message will print, then a `crtl-C` or other break command is required to return to the prompt.

## Proposed changes

Use `anyhow::Context` to provide information about the expectation when using this command, and return the `Error` from the call.
Now if the command is used, the result is:

```
A default project or project parameter is required.
help: Please report this issue, with a copy of your logs, to https://github.com/build-trust/ockam/issues

Version: <version no> hash: <hash>
```

## Checks

- [X] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [X] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [X] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

### CODE REVIEW

File: implementations/rust/ockam/ockam_command/src/util/orchestrator_api.rs [hunk 1]
```diff
@@ -1,11 +1,11 @@
 use std::path::PathBuf;
 
+use anyhow::Context;
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_command/src/util/orchestrator_api.rs]: You can write this as `use anyhow::Context as _` to avoid the collision with `ockam::Context`. That way you won't have to modify the `ctx: &'a Context,` instances.

Comment (seve-martinez) [reply implementations/rust/ockam/ockam_command/src/util/orchestrator_api.rs]: TIL! Thanks, I updated the file.

**Review by adrianbenavides — APPROVED** [review]
LGTM! Thanks @seve-martinez for taking the time with this and congrats on your first Ockam PR merged 🥳

**Review by etorreborre — APPROVED** [review]

**Review by SanjoDeundiak — APPROVED** [review]
