### PR TITLE
fix(rust): Abort on ockam enroll --output json

### LINKED ISSUE #6119: Improve `ockam enroll --output json` by making it fail right away
# Current behavior

When you run `ockam enroll --output json` whether you have enrolled (using `ockam enroll`) or not, it looks like the following screenshot.

Image

- It does not show a one-time code
- But it spawns a local browser
- Since no code is shown there is no way to type in the correct code in the browser

# Desired behavior

When `ockam enroll --output json` is passed it, it should exit immediately and report that this is an invalid flag that can't be passed in.

Please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/enroll/command.rs#L38).

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

### PR DESCRIPTION
**Pull request by kriogenia**
## Current behavior

When you run ockam enroll --output json whether you have enrolled (using ockam enroll) or not, it looks like the following screenshot.

-  It does not show a one-time code
-  But it spawns a local browser
-  Since no code is shown there is no way to type in the correct code in the browser

## Proposed changes

Add an early exit to the command `ockam enroll` when used with the `--output json` flag as it's not admitted in this command.

Close #6119

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

File: implementations/rust/ockam/ockam_command/src/enroll/command.rs [hunk 1]
```diff
@@ -51,6 +52,14 @@ pub struct EnrollCommand {
...
 impl EnrollCommand {
     pub fn run(self, opts: CommandGlobalOpts) {
+        if opts.global_args.output_format == OutputFormat::Json {
+            let _ = opts
+                .terminal
+                .stdout()
+                .json("The flag --output json is invalid for this command.")
+                .write_line();
+            return;
+        }
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_command/src/enroll/command.rs]: To make sure that scripts can detect that this is an error, we should return an error instead of printing text to stdout.

To do that, this check should happen inside the `rpc` function, just before calling `run_impl`.

Comment (kriogenia) [reply implementations/rust/ockam/ockam_command/src/enroll/command.rs]: Fixed

**Review by adrianbenavides — APPROVED** [review]
Perfect, thank you @kriogenia 🙏  Will get merged soon!
