### PR TITLE
tests(rust): fix flaky transport tests

### LINKED ISSUE #2720: Failing test in websocket transport
This test fails occasionally:
https://github.com/build-trust/ockam/runs/6336949886?check_suite_focus=true

### PR DESCRIPTION
**Pull request by adrianbenavides**
Transport tests that were using a random port to create the "listener" sides were failing when the selected port was already used by another process. These changes add a loop to retry binding a transport until it succeeds.

It also adds a small change to the `test` macro so that we don't have to explicitly stop the context at the end of every test.

Fixes https://github.com/build-trust/ockam/issues/2720

### CODE REVIEW

**Comment by twittner** [comment]
Can we not have the operating system assign us a port number by using 0?

**Comment by adrianbenavides** [comment]
> Can we not have the operating system assign us a port number by using 0?

We should be able to by modifying the `listen` and `create_outlet` methods on the transports crates to return the assigned address. That would definitely be an improvement. Maybe we could leave this for a separate PR? Just to ensure that the tests are stable now without changing any production code.

Thanks for the tip @twittner!

**Comment by adrianbenavides** [comment]
I've added the changes suggested by @twittner to remove the "random port" logic altogether.

**Comment by SanjoDeundiak** [comment]
How do we manage to collide picking random port from 10000 to 65535?
P.S. Can we reduce the scope of this PR to fixing tests only? Would be glad to discuss macro update in separate PR

**Comment by adrianbenavides** [comment]
> How do we manage to collide picking random port from 10000 to 65535?

In my case, I had some os processes running on ports 19455, 42849 and 50586. I don't know if a similar case could happen in CI, but knowing what ports are available is out of our control I guess, so it should be best if we can assign a port automatically by the os. Also if tests were to be run in parallel, chances would definitely be there, although this fix won't solve the problem toralf outlined here: https://github.com/build-trust/ockam/issues/2730.

> P.S. Can we reduce the scope of this PR to fixing tests only? Would be glad to discuss macro update in separate PR

Sure, done!

File: implementations/rust/ockam/ockam_transport_tcp/tests/send_receive.rs [hunk 1]
```diff
@@ -1,33 +1,27 @@
...
-    let bind_address = format!("127.0.0.1:{}", rand_port);
-    let bind_address = bind_address.as_str();
+    let listener_address;
 
     let _listener = {
         let transport = TcpTransport::create(ctx).await?;
-        transport.listen(bind_address).await?;
+        listener_address = transport.listen("127.0.0.1:0").await?;
         ctx.start_worker("echoer", Echoer).await?;
     };
```
Comment (twittner) [inline implementations/rust/ockam/ockam_transport_tcp/tests/send_receive.rs]: How about removing the `let _listener` block and initialising `listener_address` directly? E.g.

```rust
let transport = TcpTransport::create(ctx).await?;
let listener_address = transport.listen("127.0.0.1:0").await?;
ctx.start_worker("echoer", Echoer).await?;
```

File: implementations/rust/ockam/ockam_transport_tcp/tests/send_receive.rs [hunk 2]
```diff
@@ -55,33 +50,27 @@ impl Worker for Echoer {
...
+        .sample_iter(&rand::distributions::Alphanumeric)
+        .take(256)
+        .map(char::from)
+        .collect();
 
-    let tx_address = transport.connect(bind_address).await?;
+    let tx_address = transport.connect(&listener_address).await?;
 
-    let r = route![(TCP, format!("localhost:{}", rand_port)), "echoer"];
+    let r = route![(TCP, listener_address.clone()), "echoer"];
```
Comment (twittner) [inline implementations/rust/ockam/ockam_transport_tcp/tests/send_receive.rs:63]: `SocketAddr` implements `Copy`, so in theory the clone call is not needed.

**Review by twittner — DISMISSED** [review]
:+1:

**Review by spacekookie — DISMISSED** [review]

File: implementations/rust/ockam/ockam_transport_tcp/src/transport.rs [hunk 3]
```diff
@@ -1,8 +1,11 @@
-use crate::{parse_socket_addr, TcpOutletListenWorker, TcpRouter, TcpRouterHandle};
+use std::net::SocketAddr;
```
Comment (SanjoDeundiak) [inline implementations/rust/ockam/ockam_transport_tcp/src/transport.rs]: The right import would be 
```
use ockam_core::compat::net::SocketAddr;
```
@antoinevg could you please share your recommendations on imports?

**Review by SanjoDeundiak — DISMISSED** [review]
Looks great, one fix is required though

File: implementations/rust/ockam/ockam_transport_tcp/tests/send_receive.rs (hunk 2 above)
Comment (adrianbenavides) [reply implementations/rust/ockam/ockam_transport_tcp/tests/send_receive.rs:63]: It expects a `String` there, and also a few lines above that (when calling `transport.connect(&listener_address)`). It looks like cloning that string is the less painful option.

File: implementations/rust/ockam/ockam_transport_tcp/tests/send_receive.rs (hunk 1 above)
Comment (adrianbenavides) [reply implementations/rust/ockam/ockam_transport_tcp/tests/send_receive.rs]: Absolutely, thanks!

File: implementations/rust/ockam/ockam_transport_tcp/tests/send_receive.rs (hunk 2 above)
Comment (twittner) [reply implementations/rust/ockam/ockam_transport_tcp/tests/send_receive.rs:63]: Ah sorry! You are right of course, I missed that you had it converted to a string again in line 56.

File: implementations/rust/ockam/ockam_transport_tcp/src/transport.rs (hunk 3 above)
Comment (adrianbenavides) [reply implementations/rust/ockam/ockam_transport_tcp/src/transport.rs]: I've replaced the `std` imports with the `ockam_core::compat` ones.

**Review by twittner — DISMISSED** [review]

**Review by mrinalwadhwa — CHANGES_REQUESTED** [review]
@adrianbenavides It looks like `commitlint` [ignores](https://github.com/conventional-changelog/commitlint/blob/914782aad70d353baf4d9fbbf9824c0211241484/%40commitlint/is-ignored/src/is-ignored.test.ts#L96) commits of the form:

```
Revert "test(rust): fix flaky transport tests"
```

That was surprising to me. We should add some overriding lints tests for it.

Since in out workflow commits get rebased and moved around, its better to avoid referring to older commits and instead just describe the change that is in a patch/commit.

**Comment by adrianbenavides** [comment]
> @adrianbenavides It looks like `commitlint` [ignores](https://github.com/conventional-changelog/commitlint/blob/914782aad70d353baf4d9fbbf9824c0211241484/%40commitlint/is-ignored/src/is-ignored.test.ts#L96) commits of the form:
> 
> ```
> Revert "test(rust): fix flaky transport tests"
> ```
> 
> That was surprising to me. We should add some overriding lints tests for it.
> 
> Since in out workflow commits get rebased and moved around, its better to avoid referring to older commits and instead just describe the change that is in a patch/commit.

Yeah, I didn't think about changing the auto-generated message after the revert. I've changed it now!

**Review by mrinalwadhwa — APPROVED** [review]
