### PR TITLE
Complain deleting nonexistent listeners

### LINKED ISSUE #4972: Do not print that a secure channel listener was successfully deleted when it is not the case
### Observed behavior

`ockam` reports that a secure channel listener has been deleted even if it does not exist

### Steps to reproduce

While the `_missing_` secure channel listener does not exist the console still prints out that the listener has been deleted:
```
Deleted secure-channel listener with address '/service/_missing_' on node 'n1'
```

### Expected behavior

`ockam` should display a message saying that the secure channel address has not been found and only display that the secure channel listener has been deleted when the deletion is successful.

### Diagnostic

The `delete` command for secure channels listeners is implemented:

 - [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/secure_channel/listener/delete.rs#L40) for sending a request to the node
 - and [there](https://github.com/build-trust/ockam/blob/55b53a95c3fec34ce60c3ec700fcca9248e9bc87/implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs#L477) for building the response

However we can see that:

 - the function in `ockam_api` does not consider the case where the listener might not exist. It should return `Ok(NotFound)`
 - the function in `ockam_command` prints the same successful answer whether the action was successful or not

### Ockam Version

0.87.0

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

### PR DESCRIPTION
**Pull request by i-b-o-t**
Addresses #4972 

> Do not print that a secure channel listener was successfully deleted when it is not the case

### CODE REVIEW

File: implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs [hunk 1]
```diff
@@ -488,20 +487,19 @@ impl NodeManagerWorker {
...
-                Some(addr)
+                payload = Some(addr);
+                Response::ok(id)
             }
-            Err(err) => {
-                trace!(%addr, %err, "Error removing secure channel listener");
-                None
+            None => {
+                trace!(%addr, "Error removing secure channel listener");
+                Response::not_found(id)
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs]: I think this change here is all you need to check the `NotFound` error on the command side. 

You don't even need to put the payload behind an `Option` because you can check the response code from the header directly. This is done automatically when you call the ` rpc.is_ok()?;` function. If that call doesn't return an error, then you are good to parse the response body.

**Review by adrianbenavides — COMMENTED** [review]
Hey @i-b-o-t , thanks for submitting this PR! I think it's pretty close to completion, just a small fix and will be ready. Let me know if you still want to work on it 👍 

I'll leave it as a `draft` in the meantime. Feel free to move it back to `ready to review` when you see fit!

**Comment by i-b-o-t** [comment]
> Hey @i-b-o-t , thanks for submitting this PR! I think it's pretty close to completion, just a small fix and will be ready. Let me know if you still want to work on it +1
> 
> I'll leave it as a `draft` in the meantime. Feel free to move it back to `ready to review` when you see fit!

Thanks for the reminder! Yes, I still would like to complete it. Just pulled it up - getting back to it.

**Comment by adrianbenavides** [comment]
Awesome, thanks @i-b-o-t! Let us know whenever it's ready to review or if you have any questions 👍

File: implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs (hunk 1 above)
Comment (i-b-o-t) [reply implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs]: Yes, that approach is nicer. I consistently went the down route taken for the "show" subcomand; 0214630

**Comment by i-b-o-t** [comment]
@adrianbenavides 

> Awesome, thanks @i-b-o-t! Let us know whenever it's ready to review or if you have any questions :+1:

I clicked that button not sure will notify.. :innocent: 

The changes are in individual commits for easy reviewing, intended to be compacted using `--autosquash` (I'm only rewriting to rebase onto updated `develop`). I don't know how squashing will affect the signing of the commits, so let me know in case you want me to perform the compaction for you once we're good to merge.

**Review by adrianbenavides — APPROVED** [review]
Looks perfect, thanks @i-b-o-t ! You can go ahead and squash the commits (the signing should not be affected) and will be ready to merge 🚀

**Comment by i-b-o-t** [comment]
@adrianbenavides :

> You can go ahead and squash the commits

OK, now they're all one.
