### PR TITLE
delete node interactively

### LINKED ISSUE #6450: Make `ockam node delete` (no args) interactive by asking the user to choose from a list of nodes to delete (tuify)
# Current behavior

When a user runs `ockam node delete` without any arguments, currently they are prompted to delete the default node. Here's a screenshot of this.

Image

# Desired behavior

Instead of deleting the default node, change the behavior of this command so that it becomes interactive with the user. Note that this can only be allowed to happen if:
- the terminal is interactive, and,
- the [`--no-input`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L265) or `--quiet` flags have *not* been passed, and,
- no arguments have been passed in to the command.

This what the user flow should look like in interactive mode.
1) Use the [tuify](https://crates.io/crates/r3bl_tuify) crate's `select_from_list()` function to ask the user to select from a list of node names. They should be able to make multiple selections. If there are none, then simply display a message saying that none exist (not an error) and exit.

2) Once the user has made their selection(s), display a confirmation prompt letting the user know that that a destructive operation is about to take place with the node names they have selected. Use `select_from_list()` to display this prompt. They should be able to make a single selection.
   - If they have made no selections then exit by displaying a message to the user letting them know they did not make any selection.

3) If they choose "YES", then delete each selected node, and display a success / failure message for each node that got deleted. 
   - If an operation succeeds then use the ✅ emoji as a prefix for the message. 
   - And if it fails, then use the ⚠️ emoji as a prefix for the message.

> The following is a video showing a generic user flow that shows the user experience when a user is asked to choose a from a list of "things". Then an action is performed on each "thing". Finally status information is reported for each action that is performed on each "thing". Please note that this flow is *not* specific to this issue. 
> Image
>  https://asciinema.org/a/612547

# Implementation details

- If it hasn't been added already, please add the [tuify](https://crates.io/crates/r3bl_tuify) crate the `Cargo.toml` file [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/Cargo.toml#L55) by adding this line `r3bl_tuify = "0.1.16"` to the `[dependencies]` section.
- You can learn more about how to use the `select_from_list()` in the tuify crate [here](https://docs.rs/r3bl_tuify/latest/r3bl_tuify/). Here is an [example](https://github.com/r3bl-org/r3bl_rs_utils/blob/ockam-demo/tuify/examples/main_interactive.rs) that is very similar to the steps you might have to take for this issue.
- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L255) you can look at to detect when a terminal is interactive or not.
- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/delete.rs#L43) you can look at to see where the `ockam node delete` command is implemented.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

### PR DESCRIPTION
**Pull request by mickm3n**
For implementing https://github.com/build-trust/ockam/issues/6450

## Current behavior

When a user runs `ockam node delete` without any arguments, currently they are prompted to delete the default node. Here's a screenshot of this.

Image

## Proposed changes

Instead of deleting the default node, change the behavior of this command so that it becomes interactive with the user. Note that this can only be allowed to happen if:

* the terminal is interactive, and,
* the `--no-output` or `--quiet` flags have _not_ been passed, and,
* no arguments have been passed in to the command.

When there one or more nodes could be deleted, after a user runs `ockam node delete`, the user will see
* image
* If the user doesn't select one and press Enter, the user will see
  * image
* But if the user does select and press Enter, the user will see
  * image
  * After selecting `YES`
    * image

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

**Comment by mickm3n** [comment]
@nazmulidris I don't know how to make node deletion fail, so I haven't tested the failed scenario. If you have any advice, I could try it.

Any advice is welcome!

**Comment by nazmulidris** [comment]
> I don't know how to make node deletion fail, so I haven't tested the failed scenario. If you have any advice, I could try it. Any advice is welcome!

@adrianbenavides Any thoughts on this?

File: implementations/rust/ockam/ockam_command/src/node/util.rs [hunk 1]
```diff
@@ -34,6 +34,15 @@ pub fn delete_node(opts: &CommandGlobalOpts, name: &str, force: bool) -> miette:
...
 }
 
+pub fn get_all_node_names(opts: &CommandGlobalOpts) -> miette::Result<Vec<String>> {
+    let nodes_states = opts.state.nodes.list()?;
+    let mut nodes = Vec::new();
+    for s in nodes_states {
+        nodes.push(s.name().to_string());
+    }
+    Ok(nodes)
+}
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_command/src/node/util.rs]: There is a function for this already: `opts.state.nodes.list_items_names()?`

File: implementations/rust/ockam/ockam_command/src/node/delete.rs [hunk 2]
```diff
@@ -40,32 +40,90 @@ impl DeleteCommand {
...
+            if opts
+                .terminal
+                .confirm_interactively(format!(
+                    "Would you like to delete these items : {:?}?",
+                    selected_list
+                ))
+                .unwrap_or(false)
+            {
+                let (deleted_nodes, delete_fail_nodes_with_error) =
+                    delete_selected_nodes(&opts, selected_list, cmd.force)?;
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_command/src/node/delete.rs]: This could be replaced by:

```rust
let res = node_names
    .iter()
    .map(|name| (name, opts.state.nodes.delete_sigkill(name, cmd.force)))
    .collect::<Vec<_>>();
```

File: implementations/rust/ockam/ockam_command/src/node/delete.rs [hunk 3]
```diff
@@ -40,32 +40,90 @@ impl DeleteCommand {
...
+
+                for deleted_node in deleted_nodes {
+                    println!("✅ Deleted Node: '{}'", &deleted_node);
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_command/src/node/delete.rs]: All the `println` calls should be replaced by calls to `opts.terminal.write_line`. Also, you should use `fmt_ok` or the other [fmt helpers](https://github.com/build-trust/ockam/blob/dcae9ee9a2a343a13beaf78d29b0efd66e04555b/implementations/rust/ockam/ockam_command/src/terminal/fmt.rs) instead of embedding emojis directly.

**Review by adrianbenavides — COMMENTED** [review]
> @nazmulidris I don't know how to make node deletion fail, so I haven't tested the failed scenario. If you have any advice, I could try it.

The easiest way would be to manually delete the `pid` file in the node's state directory before deleting it through the command.

**Comment by mickm3n** [comment]
Thanks for your review. I'll check.

**Comment by mickm3n** [comment]
Hi @adrianbenavides, I fix all the problems in your feedback. Please help review again 🙏

I successfully triggered the failed condition by modifying the pid in the node's pid file.
image

However, if I remove the PID file, the result will be succeeded, but the node process will remain alive. I have no idea how to trace the problem; maybe we should create an issue.

**Comment by adrianbenavides** [comment]
> Hi @adrianbenavides, I fix all the problems in your feedback. Please help review again 🙏
> 
> I successfully triggered the failed condition by modifying the pid in the node's pid file. image

Yeah, that's right, you had to modify it, not remove it. Removing the PID file is expected to have no effect when removing the node, my mistake!

File: implementations/rust/ockam/ockam_command/src/node/delete.rs [hunk 4]
```diff
@@ -40,32 +41,94 @@ impl DeleteCommand {
     }
 }
 
+enum DeleteMode {
+    All,
+    Selected(Option<Vec<String>>),
+    Single(Option<String>),
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_command/src/node/delete.rs]: Perhaps, instead of using `Option` in these two variants, you could add a new variant called `None`, so that you don't have to check the `Option` when deleting the nodes. It would also help removing the `unwrap` from line 96: `let selected_node_names = option_selected_node_names.unwrap();`

To make things even easier to understand, I would add a `Default` variant that should be used when `DeleteCommand`'s `node_name` is `None`.

File: implementations/rust/ockam/ockam_command/src/terminal/mod.rs [hunk 5]
```diff
@@ -252,8 +259,54 @@ impl<W: TerminalWriter> Terminal<W> {
...
+        match &user_input {
+            Some(it) => {
+                if it.contains(&"YES".to_string()) {
+                    return Some(true);
+                } else {
+                    return Some(false);
+                }
+            }
+            None => Some(false),
+        }
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_command/src/terminal/mod.rs]: This never returns `None` right? Could we return a plain `bool`?

File: implementations/rust/ockam/ockam_command/src/node/delete.rs [hunk 6]
```diff
@@ -40,32 +41,94 @@ impl DeleteCommand {
...
+                            fmt_ok!("Deleted Node: '{}'\n", name)
+                        } else {
+                            fmt_warn!(
+                                "Failed to delete Node: '{}', Error: '{}'\n",
+                                name,
+                                res.as_ref().unwrap_err()
+                            )
+                        }
+                    })
+                    .collect::<String>();
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_command/src/node/delete.rs]: You can simplify this as follows (no need to show the error to the user):

```rust
let output = selected_node_names
    .iter()
    .map(|name| {
        if opts.state.nodes.delete_sigkill(name, cmd.force).is_ok() {
            fmt_ok!("Node {name} deleted\n")
        } else {
            fmt_warn!("Failed to delete Node '{name}'\n")
        }
    })
    .collect::<String>();
```

**Review by adrianbenavides — COMMENTED** [review]
I've left some more comments. Looking pretty great so far!

**Comment by mickm3n** [comment]
@adrianbenavides, I appreciate your feedback. You saved me from the Option and iterator hell. I learned a lot. I fixed all of them; please help review them again. Many thanks!

**Review by adrianbenavides — DISMISSED** [review]
Looks fantastic and ready to merge! Thank you so much for this contribution @mickm3n, will get merged soon 🥳

**Review by nazmulidris — APPROVED** [review]
Looks great to me! 🎉
