### PR TITLE
fix(rust): improve markdown help renderer

### LINKED ISSUE #4547: `ockam markdown` command renders logs in the examples sections
### Observed behavior

```
cargo run --bin ockam markdown
```

The examples sections in markdown files look like this:

```
### Examples

[1;4mAbout:
[0m    An Ockam Authority node is an Ockam node running a limited set of services used by other nodes to:
        - issue credentials
        - create enrollment tokens
        - accept enrollment tokens
        - authenticate identities as project members

    Those services are accessible by creating a secure channel over a TCP connection at `tcp-listener-address`.

[1;4mExamples:
[0m[38;2;192;197;206m    [38;2;101;115;126m#[38;2;101;115;126m Create an authority node which can be accessed by users of project 93c6455c5f[38;2;101;115;126m
[38;2;192;197;206m    [38;2;101;115;126m#[38;2;101;115;126m The default node name is 'authority'.[38;2;101;115;126m
[38;2;192;197;206m    [38;2;143;161;179m$[38;2;192;197;206m ockam authority create [38;2;192;197;206m\
[38;2;191;97;106m          --[38;2;191;97;106mtcp-listener-address[38;2;192;197;206m 127.0.0.1:4200 [38;2;192;197;206m\
[38;2;191;97;106m          --[38;2;191;97;106mproject-identifier[38;2;192;197;206m 93c6455c5f [38;2;192;197;206m\
[38;2;191;97;106m          --[38;2;191;97;106mtrusted-identities[38;2;192;197;206m [38;2;192;197;206m"[38;2;163;190;140m[{[38;2;150;181;180m\"[38;2;163;190;140midentifier[38;2;150;181;180m\"[38;2;163;190;140m: [38;2;150;181;180m\"[38;2;163;190;140mP6c20e814b56579306f55c64e8747e6c1b4a53d9a3f4ca83c252cc2fbfc72fa94[38;2;150;181;180m\"[38;2;163;190;140m, [38;2;150;181;180m\"[38;2;163;190;140mattributes[38;2;150;181;180m\"[38;2;163;190;140m: {[38;2;150;181;180m\"[38;2;163;190;140mockam-role[38;2;150;181;180m\"[38;2;163;190;140m: [38;2;150;181;180m\"[38;2;163;190;140menroller[38;2;150;181;180m\"[38;2;163;190;140m}}][38;2;192;197;206m"[38;2;192;197;206m
[38;2;192;197;206m
[38;2;192;197;206m    [38;2;101;115;126m#[38;2;101;115;126m Create an authority node which can be accessed by users of project 93c6455c5f[38;2;101;115;126m
[38;2;192;197;206m    [38;2;101;115;126m#[38;2;101;115;126m Trusted identities come from a file which is always reloaded where searching for an identity attribute[38;2;101;115;126m
[38;2;192;197;206m    [38;2;143;161;179m$[38;2;192;197;206m ockam authority create [38;2;192;197;206m\
[38;2;191;97;106m          --[38;2;191;97;106mtcp-listener-address[38;2;192;197;206m 127.0.0.1:4200 [38;2;192;197;206m\
[38;2;191;97;106m          --[38;2;191;97;106mproject-identifier[38;2;192;197;206m 93c6455c5f [38;2;192;197;206m\
[38;2;191;97;106m          --[38;2;191;97;106mreload-from-trusted-identities-file[38;2;192;197;206m trust-anchors.json[38;2;192;197;206m
[38;2;192;197;206m
[38;2;192;197;206m    [38;2;101;115;126m#[38;2;101;115;126m Delete an authority node[38;2;101;115;126m
[38;2;192;197;206m    [38;2;143;161;179m$[38;2;192;197;206m ockam node delete authority[38;2;192;197;206m
[0m

```

### Steps to reproduce

On the current develop:

```
cargo run --bin ockam markdown
```

### Expected behavior

Render the example snippets

### Ockam Version

develop

### PR DESCRIPTION
**Pull request by mrinalwadhwa**
fixes #4547

### CODE REVIEW

File: implementations/rust/ockam/ockam_command/src/docs.rs [hunk 1]
```diff
@@ -35,45 +35,60 @@ static THEME: Lazy<Option<Theme>> = Lazy::new(|| {
     Some(theme)
 });
 
+fn is_markdown() -> bool {
+    match std::env::var("OCKAM_HELP_RENDER_MARKDOWN") {
```
Comment (etorreborre) [inline implementations/rust/ockam/ockam_command/src/docs.rs:39]: We could refactor all the places where we read environment variables to act a bit more like a command line option library:

 - with parsers giving you back a `bool`, a `String`, even a `Vec<T>` when `T` has a parser and we read comma-delimited values for example. This way we are alway consistent with how we encode `true` in environment variables
 - where we return a `Result` if something cannot be parsed. For example if I enter `OCKAM_HELP_RENDER_MARKDOWN=trua` (typo) I will get an error right away and not some silent default behaviour
 - with default values to be more explicit about what `Err(_e) => false` means

File: implementations/rust/ockam/ockam_command/src/docs.rs [hunk 2]
```diff
@@ -35,45 +35,60 @@ static THEME: Lazy<Option<Theme>> = Lazy::new(|| {
...
+    } else {
+        let syntax_highlighted = highlight_syntax(body.to_string());
+        Box::leak(syntax_highlighted.into_boxed_str())
+    }
 }
 
 #[allow(unused)]
 pub(crate) fn before_help(body: &str) -> &'static str {
-    Box::leak(highlight_syntax(body.to_string()).into_boxed_str())
+    if is_markdown() {
```
Comment (etorreborre) [inline implementations/rust/ockam/ockam_command/src/docs.rs]: We should refactor that code with L.53, and L. 71 so that we don't have to introduce more duplication or forget about the `is_markdown` case when we introduce a new section.

**Review by etorreborre — DISMISSED** [review]
It works (I tested it) and I think we can improve the code in 2 places. I can do the small refactor now and open an issue for the env var refactoring

**Comment by etorreborre** [comment]
I created an issue for the refactoring of environment variables: https://github.com/build-trust/ockam/issues/4549

File: implementations/rust/ockam/ockam_command/src/docs.rs (hunk 1 above)
Comment (mrinalwadhwa) [reply implementations/rust/ockam/ockam_command/src/docs.rs:39]: That sounds awesome, It would also be good to have a place in help that shows the environment variables that can be set.

Comment (etorreborre) [reply implementations/rust/ockam/ockam_command/src/docs.rs:39]: Great idea, I created an issue for it: https://github.com/build-trust/ockam/issues/4554

**Review by davide-baldo — APPROVED** [review]
