### PR TITLE
fix(rust): use the correct policies in inlets/outlets created by kafka services

### LINKED ISSUE #7544: Delete all related data from SQL storage when deleting a node
### Observed behavior

Currently, when a node is deleted, only data in `node` table is deleted.

### Steps to reproduce

Create a node, create a related to node data (attributes entry, policy, etc.)

### Desired behavior

All data tied to that node should be deleted from the sql storage. Currently, the tables with such data are: `credential`, `identity_attributes`, `node_project`, `policy`, 

### Ockam Version

0.115.0

### PR DESCRIPTION
**Pull request by adrianbenavides**
- `kafka consumer` and `kafka producer` commands expect a `project_route` argument, which implies that the services created in those commands will have a special policy to check the project id
- `kafka outlet` and `kafka direct` commands do not expect any project related data, so it uses a policy depending on the target route 

Additionally, it closes https://github.com/build-trust/ockam/issues/7544

### CODE REVIEW

File: implementations/rust/ockam/ockam_api/src/kafka/secure_channel_map.rs [hunk 1]
```diff
@@ -155,10 +155,10 @@ impl<F: RelayCreator> Clone for KafkaSecureChannelControllerImpl<F> {
 }
 
 /// Describe to reach the consumer node:
-/// either directly or through a relay with a relay
+/// either directly or through a relay
 #[derive(Clone)]
 pub(crate) enum ConsumerNodeAddr {
-    Direct(Option<MultiAddr>),
+    Direct(MultiAddr),
```
Comment (davide-baldo) [inline implementations/rust/ockam/ockam_api/src/kafka/secure_channel_map.rs:161]: In direct mode, you can take the two roles, consumer or producer, the producer will specify the consumer in the `consumer_route` argument, but the consumer won't have anything to specify (unless both nodes have both roles).
Maybe we can add a third `None` option?

File: implementations/rust/ockam/ockam_api/src/nodes/service/kafka_services.rs [hunk 2]
```diff
@@ -181,29 +170,39 @@ impl InMemoryNode {
...
+        let outlet_policy_expression = if consumer_route.starts_with(Project::CODE) {
+            let project_identifier = self
+                .cli_state
+                .get_node_project(&self.node_name)
+                .await?
+                .identity
+                .ok_or(ApiError::core("NodeManager has no project"))?;
+            Some(kafka_policy_expression(&project_identifier))
+        } else {
+            None
```
Comment (davide-baldo) [inline implementations/rust/ockam/ockam_api/src/nodes/service/kafka_services.rs]: In case we are not passing through a project, we can add an explicit policy. This policy should be the default one, but it's subject to change, and it would be more robust to repeat it here: `let check_credential_expression =
                    Expr::Ident(format!("{}.{}", SUBJECT_KEY, ABAC_HAS_CREDENTIAL_KEY))`

File: implementations/rust/ockam/ockam_api/src/kafka/secure_channel_map.rs (hunk 1 above)
Comment (adrianbenavides) [reply implementations/rust/ockam/ockam_api/src/kafka/secure_channel_map.rs:161]: Okey, I didn't know that. I think adding a third option will make things more understandable.

File: implementations/rust/ockam/ockam_api/src/nodes/service/kafka_services.rs (hunk 2 above)
Comment (adrianbenavides) [reply implementations/rust/ockam/ockam_api/src/nodes/service/kafka_services.rs]: Will do that!

**Review by davide-baldo — APPROVED** [review]
