### PR TITLE
fix(rust): return error when maximum message length is exceeded

### LINKED ISSUE #6880: detect, log and discard messages too large to be send on the wire
### Observed behavior

Currently each individual ockam message is limited to up to `2^16` bytes when serialized.   On the wire,  messages are prepended with a 2bytes header indicating their length, following the encoded message itself. 

But this is not really enforced when serializing.   The [size advertised on the wire is just truncated](https://github.com/build-trust/ockam/blob/258fa2d4bf1feeee8b8801c7aac1fdd22de1530d/implementations/rust/ockam/ockam_transport_tcp/src/workers/sender.rs#L240), and the message is sent anyway

### Steps to reproduce

Can be easily tested using the existing examples on `examples/rust/get_started`  

- Modify  [04-routing-over-transport-initiator.rs](https://github.com/build-trust/ockam/blob/develop/examples/rust/get_started/examples/04-routing-over-transport-initiator.rs#L19) so the message it sent is larger than `2^16` 
- Run `cargo run --example 04-routing-over-transport-responder` to start the listener side
- Run `cargo run --example 04-routing-over-transport-initiator` to launch the connecting side

The message will be tried to be send anyway,  and an error will be reported on the responder side. 

### Expected behavior

We *must* detect  if the msg size is larger than `2^16` , and if that's the case  *do not send* the message, instead return a [TransportError](https://github.com/build-trust/ockam/blob/c8ed28a7b7ea32559774c07fe46c4c3cd5dacbc2/implementations/rust/ockam/ockam_transport_core/src/error.rs#L9) here [when serializing the msg](https://github.com/build-trust/ockam/blob/258fa2d4bf1feeee8b8801c7aac1fdd22de1530d/implementations/rust/ockam/ockam_transport_tcp/src/workers/sender.rs#L236)

That must be done on all transport where applicable, not only the TCP one (for example the [uds one is affected too](https://github.com/build-trust/ockam/blob/c8ed28a7b7ea32559774c07fe46c4c3cd5dacbc2/implementations/rust/ockam/ockam_transport_uds/src/workers/sender.rs#L295) )

### Ockam Version

v0.102.0

### PR DESCRIPTION
**Pull request by shautvast**
## Current behavior

Currently messages sent over tcp and udp are not checked for the max length of 65535 bytes. The message is truncated and errors can occur when deserializing.

## Proposed changes

The PR fixes https://github.com/build-trust/ockam/issues/6880. It adds a check for maximum length and returns an Error when it's exceeded.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [x] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

### CODE REVIEW

File: implementations/rust/ockam/ockam_transport_core/src/transport.rs [hunk 1]
```diff
@@ -5,6 +5,9 @@ use ockam_core::{async_trait, Address, Result, TransportType};
 /// At minimum, a Transport must be able
 ///  - return its type
 ///  - instantiate workers for all the addresses with that transport type in a Route
+
+pub const MAXIMUM_MESSAGE_LENGTH: usize = (u16::MAX - 2) as usize; //  - 2 bytes for length
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_transport_core/src/transport.rs]: I've been reviewing this with the team and here we should define the general limit that is common to any transport, which should be `u16::MAX`.

Then, if a specific transport needs to restrict this limit, that should be done in that transport crate (e.g. tcp, udp). We'll create a different issue or this.

File: implementations/rust/ockam/ockam_transport_tcp/src/workers/sender.rs [hunk 2]
```diff
@@ -251,3 +256,17 @@ fn prepare_message(msg: TransportMessage) -> Result<Vec<u8>> {
...
+
+#[cfg(test)]
+mod test {
+    use ockam_core::route;
+
+    use super::*;
+
+    #[test]
+    fn prepare_message_should_discard_large_messages() {
+        let msg = TransportMessage::v1(route![], route![], vec![0; u16::MAX as usize + 1]);
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_transport_tcp/src/workers/sender.rs]: Perhaps we should use the `MAXIMUM_MESSAGE_LENGTH` constant here instead of the `u16:MAX`.

**Review by adrianbenavides — COMMENTED** [review]
Hi @shautvast, thanks for submitting your PR! I've left a couple of comments to fix some minor stuff. Other than that, looks great!

File: implementations/rust/ockam/ockam_transport_core/src/transport.rs (hunk 1 above)
Comment (shautvast) [reply implementations/rust/ockam/ockam_transport_core/src/transport.rs]: I'll set it to u16:MAX

File: implementations/rust/ockam/ockam_transport_tcp/src/workers/sender.rs (hunk 2 above)
Comment (shautvast) [reply implementations/rust/ockam/ockam_transport_tcp/src/workers/sender.rs]: the counterargument would be that if someone (inadvertently) changes MAXIMUM_MESSAGE_LENGTH, then this test may fail (in case it's increased), so it would act as a guardrail for that situation.

**Comment by shautvast** [comment]
updated the PR, let me know if this addresses your comments

**Comment by shautvast** [comment]
Sorry, did a merge instead of rebase. What's the best way to fix this? new branch?

**Comment by etorreborre** [comment]
@shautvast I suggest that you recreate your branch off `develop`, cherry-pick your commits, and force-push the branch.

**Review by SanjoDeundiak — APPROVED** [review]
