### PR TITLE
feat(rust): added `tcp-inlet delete` command, hotfix to `tcp-outlet list` bug

### LINKED ISSUE #4269: Create clap command `ockam tcp-inlet delete` to delete a TCP Inlet on a node
## Summary

A node has set of TCP Inlets. This command should delete an inlet of a specific alias
```
ockam tcp-inlet delete [alias] --node [node-name]
```
The command should have a positional argument `[alias]` which is the alias of the tcp inlet to be deleted.  
The command should accept a `--node` flag, however default to the default node if one is not provided.

Code of where inlets are created and stored can be found [here](https://github.com/build-trust/ockam/blob/5cc9a66ba4adf9ed5742daaec119da7c590a2e87/implementations/rust/ockam/ockam_api/src/nodes/service/portals.rs#L103-L247).

`tcp-inlet` commands are defined [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/inlet/mod.rs).
## Expected Behavior

```sh
ockam tcp-inlet create --at /node/n2 --from 127.0.0.1:6000 --to /node/n1/service/outlet --alias "my-inlet"
...
ockam tcp-inlet delete my-inlet --node n1
Deleted TCP Inlet 'my-inlet' on node 'n1'
```

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

### PR DESCRIPTION
**Pull request by nidnogg**
## Current behavior

There is no current way to delete a `tcp-inlet` by its  `alias` and `node`.

## Proposed changes

This PR solves https://github.com/build-trust/ockam/issues/4269 by adding the `ockam tcp-inlet delete` subcommand.
Minor changes also included in this PR:
- Bats test for inlet deletion;
- Fixed a bug where `tcp-outlet list` would format outlets in an incorrect manner;
- Additional logging in `delete_outlet` and `delete_inlet` routines located in `ockam_api/src/nodes/service/portals.rs`; 

## Checks

- [X] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [X] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [X] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

### CODE REVIEW

File: implementations/rust/ockam/ockam_api/src/nodes/service/portals.rs [hunk 1]
```diff
@@ -245,6 +246,55 @@ impl NodeManagerWorker {
...
+        &mut self,
+        req: &Request<'_>,
+        dec: &mut Decoder<'_>,
+    ) -> Result<ResponseBuilder<InletStatus<'a>>> {
+        let mut node_manager = self.node_manager.write().await;
+        let DeleteInlet { alias, .. } = dec.decode()?;
+
+        let alias = alias.into_owned();
+
+        info!(%alias, "Handling request to delete inlet portal");
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_api/src/nodes/service/portals.rs:259]: To avoid writing too much in the logs, I'd only keep this `Handling request` kind of message in the `info` channel and move the rest to `debug`.

File: implementations/rust/ockam/ockam_command/tests/bats/unit.bats [hunk 2]
```diff
@@ -358,6 +358,38 @@ teardown() {
   assert_output --partial "NotFound"
 }
 
+@test "portals - delete a tcp inlet" {
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_command/tests/bats/unit.bats]: We should rename this to `portals - CRUD`.

File: implementations/rust/ockam/ockam_command/tests/bats/unit.bats [hunk 3]
```diff
@@ -358,6 +358,38 @@ teardown() {
...
+  outlet_port=5000
+  inlet_port=6000
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_command/tests/bats/unit.bats]: Make sure you don't use the same port in different tests, as they could be run in parallel.

File: implementations/rust/ockam/ockam_command/src/tcp/inlet/delete.rs [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+}
+
+/// Construct a request to delete a tcp outlet
+fn make_api_request<'a>(cmd: DeleteCommand) -> crate::Result<RequestBuilder<'a, DeleteInlet<'a>>> {
+    let payload = DeleteInlet::new(cmd.alias);
+    let request = Request::delete("/node/inlet").body(payload);
+    Ok(request)
+}
+
+fn alias_parser(arg: &str) -> Result<String> {
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_command/src/tcp/inlet/delete.rs]: I think we could abstract this and use it in the four commands that do this parsing. Maybe we could rewrite the message to something more generic: "The 'alias' argument must not contain ':' characters".

For the time being, you could put this method in a new file at `ockam_command/src/tcp/utils.rs`

File: implementations/rust/ockam/ockam_command/src/tcp/outlet/list.rs [hunk 5]
```diff
@@ -32,14 +32,14 @@ async fn run_impl(
     rpc.request(Request::get("/node/outlet")).await?;
     let response = rpc.parse_response::<OutletList>()?;
 
-    println!("Outlet:");
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_command/src/tcp/outlet/list.rs:35]: To make the `list` command consistent with other `list` commands, it should error if there are no items to show. [Here's an example](https://github.com/build-trust/ockam/blob/42f19587ab96a2330d7dbcf4e2647d6189d2f6a6/implementations/rust/ockam/ockam_command/src/node/list.rs#L33) of how it's handled in the `node list` command.

**Review by adrianbenavides — CHANGES_REQUESTED** [review]
Thanks @nidnogg for working on this! I left some comments with some tweaks that you could integrate 👍

File: implementations/rust/ockam/ockam_command/src/tcp/inlet/list.rs [hunk 6]
```diff
@@ -29,8 +29,6 @@ async fn run_impl(
     rpc.request(Request::get("/node/inlet")).await?;
     let response = rpc.parse_response::<models::portal::InletList>()?;
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_command/src/tcp/inlet/list.rs:32]: Same as https://github.com/build-trust/ockam/pull/4433/files#r1130651949

File: implementations/rust/ockam/ockam_command/src/tcp/outlet/list.rs (hunk 5 above)
Comment (nidnogg) [reply implementations/rust/ockam/ockam_command/src/tcp/outlet/list.rs:35]: Added a similar error to both inlet/outlet `list` commands in the latest commit

File: implementations/rust/ockam/ockam_command/src/tcp/inlet/delete.rs (hunk 4 above)
Comment (nidnogg) [reply implementations/rust/ockam/ockam_command/src/tcp/inlet/delete.rs]: Solved in the latest commit - for consistency though I called it `util.rs` as there seemed to be only two files named `utils.rs` in the repo as opposed to a lot of `util.rs` ones.

File: implementations/rust/ockam/ockam_command/tests/bats/unit.bats (hunk 3 above)
Comment (nidnogg) [reply implementations/rust/ockam/ockam_command/tests/bats/unit.bats]: Switched around the portals ports I'd been using

File: implementations/rust/ockam/ockam_command/tests/bats/unit.bats (hunk 2 above)
Comment (nidnogg) [reply implementations/rust/ockam/ockam_command/tests/bats/unit.bats]: Should be solved in latest commit

File: implementations/rust/ockam/ockam_api/src/nodes/service/portals.rs (hunk 1 above)
Comment (nidnogg) [reply implementations/rust/ockam/ockam_api/src/nodes/service/portals.rs:259]: Done in the latest commit, let me know if the `error!` ones should also be moved to `debug!`

File: implementations/rust/ockam/ockam_command/src/tcp/inlet/list.rs (hunk 6 above)
Comment (nidnogg) [reply implementations/rust/ockam/ockam_command/src/tcp/inlet/list.rs:32]: Also added in last commit

File: implementations/rust/ockam/ockam_command/tests/bats/unit.bats [hunk 7]
```diff
@@ -341,8 +341,8 @@ teardown() {
   assert_output --regexp "To Outlet Address: /service/.*/service/outlet"
 }
 
-@test "portals - delete a tcp outlet" {
-  port=5000
+@test "portals - tcp outlet CRUD" {
+  port=9000
```
Comment (adrianbenavides) [inline implementations/rust/ockam/ockam_command/tests/bats/unit.bats]: This port is used in another test. You could use 6002, 6003 and 6004 in your tests. I'll try to come up with something to avoid manually picking a port. Sorry about this 🙏

Comment (nidnogg) [reply implementations/rust/ockam/ockam_command/tests/bats/unit.bats]: Changed in latest commit - but I did notice a handful of other tests are sharing ports atm, notably:
- `tcp-connection CRUD`
- `tcp - create a tcp connection and then delete it`
- `portals - create an inlet/outlet pair and move tcp traffic through it` 
- `portals - create an inlet/outlet pair with relay through a forwarder and move tcp traffic through it`
(All these share port 5000)

>I'll try to come up with something to avoid manually picking a port

I could maybe implement a way to incrementally pick a port via a shell function (at the start of whichever test has to use a port) or change those ports up in the meantime in my next PR (https://github.com/build-trust/ockam/pull/4446), if you'd like.

Comment (adrianbenavides) [reply implementations/rust/ockam/ockam_command/tests/bats/unit.bats]: The port 5000 is used by the server, and that's fine for now, since we only have one server up for all the tests. The problem is sharing ports among listeners.

> I could maybe implement a way to incrementally pick a port via a shell function

The problem with that is synchronization between parallel tests, isn't it? Unless there is a way to achieve that in bash 😄

Comment (nidnogg) [reply implementations/rust/ockam/ockam_command/tests/bats/unit.bats]: > The port 5000 is used by the server, and that's fine for now, since we only have one server up for all the tests. The problem is sharing ports among listeners.
> 
> > I could maybe implement a way to incrementally pick a port via a shell function
> 
> The problem with that is synchronization between parallel tests, isn't it? Unless there is a way to achieve that in bash 😄

Are there different parallel tests that would have to use the same port, then? I figured these would be defined on a per test basis. At any rate I left those sharing `:5000` so it should be safe to merge as is.

**Review by adrianbenavides — DISMISSED** [review]
Great, looks ready to merge! Thanks @nidnogg, it will get merged as soon as we finish the current release.

**Comment by nidnogg** [comment]
@adrianbenavides I noticed a couple of conflicts in the latest merge queue updates, so I pushed a rebase solving these as far as I can see

**Review by adrianbenavides — APPROVED** [review]
